### ISSUE TITLE
flinkSQL执行消费kafka报错

### ISSUE THREAD

**Issue by zengqinchris** [DataLinkDC/dlink#142]
执行SQL
、CREATE TABLE log ( 
    database string,  
    `table` string,  
    type string,  
    ts bigint,  
    data ROW<id STRING,nick VARCHAR,sex int,mobile STRING,create_time STRING>  
) WITH ( 
    'connector.type' = 'kafka', 
    'connector.version' = 'universal', 
    'connector.topic' = 'user_unite_ods_db_xsb', 
    'connector.startup-mode' = 'earliest-offset', 
    'connector.properties.0.key' = 'group.id', 
    'connector.properties.0.value' = 'FlinkSQLtoMySQL_test02', 
    'connector.properties.1.key' = 'bootstrap.servers', 
    'connector.properties.1.value' = '192.168.0.0:9092',  
    'update-mode' = 'append', 
    'format.type' = 'json', 
    'format.derive-schema' = 'true' 
);

select database,table from log 

报错信息
[dlink] 2022-02-15 16:43:46.951 ERROR org.apache.juli.logging.DirectJDKLog 175 log - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/flink/configuration/ReadableConfig] with root cause java.lang.ClassNotFoundException: org.apache.flink.configuration.ReadableConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[dlink-admin-0.5.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at com.dlink.job.JobManager.createExecutor(JobManager.java:161) ~[dlink-core-0.5.1.jar!/:?]
	at com.dlink.job.JobManager.createExecutorWithSession(JobManager.java:182) ~[dlink-core-0.5.1.jar!/:?]
	at com.dlink.job.JobManager.init(JobManager.java:207) ~[dlink-core-0.5.1.jar!/:?]
	at com.dlink.job.JobManager.build(JobManager.java:131) ~[dlink-core-0.5.1.jar!/:?]
	at com.dlink.service.impl.StudioServiceImpl.executeFlinkSql(StudioServiceImpl.java:96) ~[classes!/:?]
	at com.dlink.service.impl.StudioServiceImpl.executeSql(StudioServiceImpl.java:81) ~[classes!/:?]
	at com.dlink.controller.StudioController.executeSql(StudioController.java:38) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) ~[druid-1.2.8.jar!/:1.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.56.jar!/:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.56.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

/opt/dlink/lib：依赖包
aggs-matrix-stats-client-6.3.1.jar                  j2objc-annotations-1.3.jar
akka-actor_2.11-2.5.21.jar                          jackson-annotations-2.7.0.jar
akka-protobuf_2.11-2.5.21.jar                       jackson-annotations-2.9.7.jar
akka-slf4j_2.11-2.5.21.jar                          jackson-core-2.11.2.jar
akka-stream_2.11-2.5.21.jar                         jackson-core-asl-1.9.11.jar
aopalliance-1.0.jar                                 jackson-databind-2.7.3.jar
avatica-core-1.17.0.jar                             jackson-databind-2.8.4.jar
checker-qual-3.5.0.jar                              jackson-dataformat-cbor-2.8.10.jar
chill_2.11-0.7.6.jar                                jackson-dataformat-smile-2.8.10.jar
chill-java-0.7.6.jar                                jackson-dataformat-yaml-2.8.10.jar
clickhouse4j-1.4.4.jar                              jackson-mapper-asl-1.9.11.jar
clickhouse-jdbc-0.2.2.jar                           jackson-module-paranamer-2.9.7.jar
commons-beanutils-1.9.3.jar                         jackson-module-scala_2.11-2.9.7.jar
commons-cli-1.3.1.jar                               janino-3.0.11.jar
commons-codec-1.9.jar                               javassist-3.24.0-GA.jar
commons-collections-3.2.2.jar                       javax.el-3.0.1-b12.jar
commons-collections4-4.1.jar                        jaxb-api-2.3.0.jar
commons-compiler-3.0.11.jar                         jedis-3.2.0.jar
commons-compress-1.20.jar                           jna-4.5.1.jar
commons-io-2.7.jar                                  joda-time-2.9.9.jar
commons-lang3-3.3.2.jar                             jopt-simple-5.0.2.jar
commons-logging-1.2.jar                             json4s-ast_2.11-3.5.3.jar
commons-math3-3.5.jar                               json4s-ast_2.11-3.6.7.jar
commons-pool-1.5.4.jar                              json4s-core_2.11-3.5.3.jar
commons-pool2-2.6.2.jar                             json4s-core_2.11-3.6.7.jar
config-1.3.3.jar                                    json4s-jackson_2.11-3.5.3.jar
curvesapi-1.04.jar                                  json4s-native_2.11-3.6.7.jar
data-flow-1.0-SNAPSHOT.jar                          json4s-scalap_2.11-3.5.3.jar
dlink-client-1.13-0.5.1.jar                         json4s-scalap_2.11-3.6.7.jar
dlink-connector-jdbc-1.13-0.5.1.jar                 jsr305-1.3.9.jar
dlink-function-0.5.1.jar                            junit-4.12.jar
dlink-metadata-clickhouse-0.5.1.jar                 kafka-clients-2.4.1.jar
dlink-metadata-mysql-0.5.1.jar                      kryo-2.24.0.jar
dlink-metadata-oracle-0.5.1.jar                     listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
dlink-metadata-postgresql-0.5.1.jar                 log4j-1.2.17.jar
easypoi-annotation-3.2.0.jar                        log4j-1.2-api-2.12.1.jar
easypoi-base-3.2.0.jar                              log4j-api-2.10.0.jar
easypoi-web-3.2.0.jar                               log4j-api-2.12.1.jar
elasticsearch-6.3.1.jar                             log4j-api-2.14.0.jar
elasticsearch-cli-6.3.1.jar                         log4j-api-scala_2.11-11.0.jar
elasticsearch-core-6.3.1.jar                        log4j-to-slf4j-2.14.0.jar
elasticsearch-rest-client-6.3.1.jar                 lombok-1.18.16.jar
elasticsearch-rest-high-level-client-6.3.1.jar      lucene-analyzers-common-7.3.1.jar
elasticsearch-secure-sm-6.3.1.jar                   lucene-backward-codecs-7.3.1.jar
elasticsearch-x-content-6.3.1.jar                   lucene-core-7.3.1.jar
error_prone_annotations-2.3.4.jar                   lucene-grouping-7.3.1.jar
failureaccess-1.0.1.jar                             lucene-highlighter-7.3.1.jar
fastjson-1.2.58.jar                                 lucene-join-7.3.1.jar
fastjson-1.2.75.jar                                 lucene-memory-7.3.1.jar
fastutil-6.5.7.jar                                  lucene-misc-7.3.1.jar
flink-annotations-1.12.0.jar                        lucene-queries-7.3.1.jar
flink-cep_2.11-1.12.0.jar                           lucene-queryparser-7.3.1.jar
flink-clients_2.11-1.12.0.jar                       lucene-sandbox-7.3.1.jar
flink-connector-base-1.12.0.jar                     lucene-spatial3d-7.3.1.jar
flink-connector-elasticsearch6_2.11-1.13.2.jar      lucene-spatial-7.3.1.jar
flink-connector-elasticsearch-base_2.11-1.13.2.jar  lucene-spatial-extras-7.3.1.jar
flink-connector-files-1.12.0.jar                    lucene-suggest-7.3.1.jar
flink-connector-jdbc_2.11-1.12.0.jar                lz4-1.3.0.jar
flink-connector-kafka_2.11-1.12.0.jar               lz4-java-1.6.0.jar
flink-connector-mysql-cdc-1.1.1.jar                 minlog-1.2.jar
flink-connector-redis_2.11-1.1.5.jar                mysql-connector-java-5.1.47.jar
flink-core-1.12.0.jar                               mysql-connector-java-8.0.22.jar
flink-csv-1.12.0.jar                                objenesis-2.1.jar
flink-dist_2.11-1.12.0.jar                          paranamer-2.8.jar
flink-file-sink-common-1.12.0.jar                   parent-join-client-6.3.1.jar
flink-hadoop-fs-1.12.0.jar                          parquet-avro-1.9.0.jar
flink-java-1.12.0.jar                               parquet-column-1.9.0.jar
flink-json-1.12.0.jar                               parquet-common-1.9.0.jar
flink-metrics-core-1.12.0.jar                       parquet-encoding-1.9.0.jar
flink-optimizer_2.11-1.12.0.jar                     parquet-format-2.3.1.jar
flink-queryable-state-client-java-1.12.0.jar        parquet-hadoop-1.9.0.jar
flink-runtime_2.11-1.12.0.jar                       parquet-jackson-1.9.0.jar
flink-runtime-web_2.11-1.12.0.jar                   platform-common-1.0-SNAPSHOT.jar
flink-scala_2.11-1.12.0.jar                         poi-3.15.jar
flink-shaded-asm-7-7.1-12.0.jar                     poi-ooxml-3.15.jar
flink-shaded-guava-18.0-12.0.jar                    poi-ooxml-schemas-3.15.jar
flink-shaded-jackson-2.10.1-12.0.jar                protobuf-java-2.5.0.jar
flink-shaded-netty-4.1.49.Final-12.0.jar            rank-eval-client-6.3.1.jar
flink-shaded-zookeeper-3-3.4.14-12.0.jar            reactive-streams-1.0.2.jar
flink-shaded-zookeeper-3.4.14.jar                   reflections-0.9.10.jar
flink-sql-connector-kafka_2.11-1.12.0.jar           scalacheck_2.11-1.15.2.jar
flink-streaming-java_2.11-1.12.0.jar                scala-compiler-2.11.12.jar
flink-streaming-scala_2.11-1.12.0.jar               scalactic_2.11-3.2.0-SNAP10.jar
flink-table_2.11-1.12.0.jar                         scala-java8-compat_2.11-0.7.0.jar
flink-table-api-java-bridge_2.11-1.12.0.jar         scala-library-2.11.12.jar
flink-table-api-scala-bridge_2.11-1.12.0.jar        scala-parser-combinators_2.11-1.0.4.jar
flink-table-blink_2.11-1.12.0.jar                   scala-reflect-2.11.12.jar
flink-table-common-1.12.0.jar                       scalatest_2.11-3.2.0-SNAP10.jar
flink-table-planner-blink_2.11-1.12.0.jar           scala-xml_2.11-1.0.5.jar
flink-table-runtime-blink_2.11-1.12.0.jar           scopt_2.11-3.5.0.jar
force-shading-1.12.0.jar                            slf4j-api-1.7.30.jar
grizzled-slf4j_2.11-1.3.2.jar                       slf4j-log4j12-1.7.30.jar
guava-30.1-jre.jar                                  snakeyaml-1.17.jar
hamcrest-core-1.3.jar                               snappy-java-1.1.4.jar
HdrHistogram-2.1.9.jar                              ssl-config-core_2.11-0.3.7.jar
hppc-0.7.1.jar                                      stax-api-1.0.1.jar
httpasyncclient-4.1.2.jar                           t-digest-3.2.jar
httpclient-4.5.jar                                  test-interface-1.0.jar
httpcore-4.4.1.jar                                  validation-api-1.1.0.Final.jar
httpcore-nio-4.4.5.jar                              xmlbeans-2.6.0.jar
httpmime-4.5.2.jar                                  zstd-jni-1.4.3-1.jar

**Comment by aiwenmo** [comment]
请使用readme中的plugins扩展所示的依赖，此外，connector依赖需要添加带有sql的依赖。

**Comment by zengqinchris** [comment]
已经修改了jar包了，还是报这个错误

![图片](https://user-images.githubusercontent.com/44901627/154190582-6431100f-a18d-4bc6-aee8-3d0a16e86ba9.png)

`user@k8s-node2:~/dlink/lib$ ll
total 116
drwxrwxrwx  2 root root  4096 Feb 16 10:59 ./
drwxrwxrwx 10 root root  4096 Feb 16 10:44 ../
-rwxrwxrwx  1 root root 34245 Feb 16 10:03 dlink-client-1.12-0.5.1.jar*
-rwxrwxrwx  1 root root 14045 Feb 16 10:59 dlink-connector-jdbc-1.12-0.6.0-SNAPSHOT.jar*
-rwxrwxrwx  1 root root  7787 Jan 24 22:25 dlink-function-0.5.1.jar*
-rwxrwxrwx  1 root root 20825 Jan 24 22:25 dlink-metadata-clickhouse-0.5.1.jar*
-rwxrwxrwx  1 root root  6633 Jan 24 22:25 dlink-metadata-mysql-0.5.1.jar*
-rwxrwxrwx  1 root root  7078 Jan 24 22:25 dlink-metadata-oracle-0.5.1.jar*
-rwxrwxrwx  1 root root  5818 Jan 24 22:25 dlink-metadata-postgresql-0.5.1.jar*
`
![图片](https://user-images.githubusercontent.com/44901627/154190649-4c8ff422-47c6-480e-843c-b09f85a94214.png)

**Comment by zengqinchris** [comment]
执行消费kafka的SQL
`CREATE TABLE log ( 
    database string,  
    `table` string,  
    type string,  
    ts bigint,  
    data ROW<id STRING,nick VARCHAR,sex int,mobile STRING,create_time STRING>  
) WITH ( 
    'connector.type' = 'kafka', 
    'connector.version' = 'universal', 
    'connector.topic' = 'xxxx', 
    'connector.startup-mode' = 'earliest-offset', 
    'connector.properties.0.key' = 'group.id', 
    'connector.properties.0.value' = 'FlinkSQLtoMySQL_test02', 
    'connector.properties.1.key' = 'bootstrap.servers', 
    'connector.properties.1.value' = '192.168.x.x:9092',  
    'update-mode' = 'append', 
    'format.type' = 'json', 
    'format.derive-schema' = 'true' 
);

select database,table from log; 


`

**Comment by zengqinchris** [comment]
执行消费kafka的SQL
`CREATE TABLE log ( 
    database string,  
    `table` string,  
    type string,  
    ts bigint,  
    data ROW<id STRING,nick VARCHAR,sex int,mobile STRING,create_time STRING>  
) WITH ( 
    'connector.type' = 'kafka', 
    'connector.version' = 'universal', 
    'connector.topic' = 'xxxx', 
    'connector.startup-mode' = 'earliest-offset', 
    'connector.properties.0.key' = 'group.id', 
    'connector.properties.0.value' = 'FlinkSQLtoMySQL_test02', 
    'connector.properties.1.key' = 'bootstrap.servers', 
    'connector.properties.1.value' = '192.168.x.x:9092',  
    'update-mode' = 'append', 
    'format.type' = 'json', 
    'format.derive-schema' = 'true' 
);

select database,table from log; 


`

**Comment by aiwenmo** [comment]
重启dlink了吗

**Comment by zengqinchris** [comment]
问题已经解决，是因为启动时没有指定依赖启动，导致依赖无法加载
`java -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false -jar -Xms512M -Xmx2048M -XX:PermSize=512M -XX:MaxPermSize=1024M ./dlink-admin-0.5.1.jar`

**Comment by awakenull** [comment]
我也是消费kafka的，怎么报错：
Caused by: java.util.ServiceConfigurationError: org.apache.flink.table.factories.Factory: Provider com.dlink.flink.catalog.factory.DlinkMysqlCatalogFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.apache.flink.table.factories.FactoryUtil.discoverFactories(FactoryUtil.java:403)
	... 92 more

**Comment by awakenull** [comment]
![image](https://user-images.githubusercontent.com/52272192/180415606-42f12752-c3c7-482b-bef4-5e1250e0b6bc.png)
