### ISSUE TITLE
[Bug] [dlink-app]Batch execution mode in Yarn-Application does not work.

### ISSUE THREAD

**Issue by roohom** [DataLinkDC/dlink#449]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

I wrote a sql like "INSERT OVERWRITE table_a SELECT id,name  FROM table_b WHERE xxx", when I submit it to execute in Yarn-Application mode, a job started in yarn cluster, but ended as failure.So I searched for the reason in the LOG file. The exception the job throwed was that a job run in streaming mode does not support overwrite. This is familiar with me, so I checked if I has clicked the "批模式" button twice. Sure I clicked, but it didn't work. I think that is a BUG.

### What you expected to happen

Here are some execption my job thorwed found in LOG file:
2022-04-26 00:38:53,465 INFO  org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - ResourceManager akka.tcp://flink@cdh003:33796/user/rpc/resourcemanager_0 was granted leadership with fencing token 00000000000000000000000000000000
2022-04-26 00:38:53,823 INFO  com.dlink.app.flinksql.Submiter                              [] - ??????? ExecutorSetting{checkpoint=0, parallelism=1, useSqlFragment=false, useStatementSet=false, savePointPath='null', jobName='HiveOverwriteAppMode', config={}}
2022-04-26 00:38:56,606 INFO  com.dlink.app.flinksql.Submiter                              [] - ???? FlinkSQL? CREATE CATALOG myhive WITH (
   'type' = 'hive',
   'default-database' = 'test',
   'hive-conf-dir' = '/etc/hive/conf'
)

......

2022-04-26 00:38:58,975 INFO  com.dlink.app.flinksql.Submiter                              [] - ???? FlinkSQL? INSERT OVERWRITE TABLE test.omd PARTITION (dt)
SELECT 
vin,
......
2022-04-26 00:39:08,961 INFO  hive.metastore                                               [] - Opened a connection to metastore, current connections: 2
2022-04-26 00:39:08,964 INFO  hive.metastore                                               [] - Connected to metastore.
2022-04-26 00:39:09,183 INFO  hive.metastore                                               [] - Closed a connection to metastore, current connections: 1
2022-04-26 00:39:09,183 WARN  org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap [] - Application failed unexpectedly: 
java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_181]
...
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [flink-dist_2.11-1.13.6.jar:1.13.6]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [flink-dist_2.11-1.13.6.jar:1.13.6]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [flink-dist_2.11-1.13.6.jar:1.13.6]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [flink-dist_2.11-1.13.6.jar:1.13.6]
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	... 11 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: <B>The main method caused an error: Streaming mode not support overwrite.<B>   
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist_2.11-1.13.6.jar:1.13.6].  
  

For more detail, I tried to prove what the message i got was right, I modified the toString method in ExecutorSetting which belongs to the module named dlink-executor. I just add the property of useBatchModel. Then  I rerun the job and i got this:
![image](https://user-images.githubusercontent.com/41498380/165147501-dce24512-7922-48a7-a25f-ad4ae7f7de5c.png)

useBatchModel=false

I think the problem here.

### How to reproduce

Just write a sql that read from a hive table and then insert overwrite to another hive table, then submit it in batch mode by yarn-application. Then you will find that .

### Version

0.6.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. It should be that useBatchMode is not saved. The latest code has been fixed.

**Comment by roohom** [comment]
> Hi. It should be that useBatchMode is not saved. The latest code has been fixed.
The problem still exists.

**Comment by aiwenmo** [comment]
> > Hi. It should be that useBatchMode is not saved. The latest code has been fixed.
> 
> The problem still exists on version 0.6.2 .

master or dev

**Comment by roohom** [comment]
> > > Hi. It should be that useBatchMode is not saved. The latest code has been fixed.
> > 
> > 
> > The problem still exists on version 0.6.2 .
> 
> master or dev

I modify the sql that select task details from the dlink_task in mysql to solve the problem 'Streaming mode not support overwrite' and I got my job worked, but it throwed another exception : 
_The LocalStreamEnvironment cannot be used when submitting a program through a client, or running in a TestEnvironment context._

So I continue to locate the root casuse, I modify some code in the class AppBatchExecutor.java like this:
**this.environment = StreamExecutionEnvironment.getExecutionEnvironment(configuration);**
The i rebuild the project and put it to HDFS, resubmit my job and I got SUCCESS.

I do not know this if be resolved on the latter version, I think it would be better. Just share some my view on using dlink, It's realy a good tool.

**Comment by aiwenmo** [comment]
Thank you very much for sharing. I will test this problem in the latest code, and then contact you.

**Comment by aiwenmo** [comment]
Hi.I checked the latest source code. As you said, the application task did not read the useBatchModel parameter. You can submit PR to fix it. thx.

**Comment by roohom** [comment]
OK, I submited my PR into dev from dev of my repo, is it OK? I'm really glad you checked that, THX.
