### ISSUE TITLE
[Bug] [client] A select sql cannot work with FlinkSqlEnv on yarn-per-job mode

### ISSUE THREAD

**Issue by roohom** [DataLinkDC/dlink#453]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

I wrote a sql like 'select count(1) from table_a' and I submit it with FlinkSqlEnv, creating a Hive dialect and using it . The job I triggered got failure status by the end. I searched the log for the reason and I got 'Only insert statement is supported now'.

Here are the main Exceptions stack I found from the web:

_2022-04-27T01:19:15.619: Exception in executing FlinkSQL:
select count(*) from test.omd 
Error message:
 org.apache.flink.table.api.TableException: Only insert statement is supported now.
	at com.dlink.executor.CustomTableEnvironmentImpl.getStreamGraphFromInserts(CustomTableEnvironmentImpl.java:150)
	at com.dlink.executor.CustomTableEnvironmentImpl.getJobGraphFromInserts(CustomTableEnvironmentImpl.java:167)
	at com.dlink.executor.Executor.getJobGraphFromInserts(Executor.java:316)
	at com.dlink.job.JobManager.submitByGateway(JobManager.java:397)
	at com.dlink.job.JobManager.executeSql(JobManager.java:293)
	at com.dlink.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:98)
	at com.dlink.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$168bea78.invoke(<generated>)_

**WHY**? It doesn't make any sense. I submit the same job on the version 0.6.1 without any failure.

### What you expected to happen

Launching the job without any problem, you know.

### How to reproduce

Just create a FlinkSqlEnv and then write a select statement , choose batch mode and submit your sql on version 0.6.2, you will find that.

### Version

0.6.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please close the statement set.
