### ISSUE TITLE
[Bug] [devops] Exception occurred (see dlink.log) after clicking cancelled job's DataMap tab

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dlink#555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Exception occurred (see dlink.log) after clicking cancelled job's DataMap tab.

------ dlink.log ----
[dlink] 2022-05-31 11:56:38 CST ERROR com.dlink.exception.WebExceptionHandler 45 unknownException - ERROR: java.lang.IllegalStateException: No operators defined in streaming topology. Cannot execute.
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getStreamGraphGenerator(StreamExecutionEnvironment.java:2105) ~[flink-dist_2.12-1.14.4.jar:1.14.4]
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.generateStreamGraph(StreamExecutionEnvironment.java:2100) ~[flink-dist_2.12-1.14.4.jar:1.14.4]
        at com.dlink.executor.CustomTableEnvironmentImpl.getStreamGraph(CustomTableEnvironmentImpl.java:202) ~[dlink-client-1.14-0.6.3.jar:?]
        at com.dlink.executor.Executor.getStreamGraph(Executor.java:248) ~[dlink-executor-0.6.3.jar!/:?]
        at com.dlink.explainer.Explainer.translateObjectNode(Explainer.java:456) ~[dlink-core-0.6.3.jar!/:?]
        at com.dlink.explainer.Explainer.explainSqlColumnCA(Explainer.java:355) ~[dlink-core-0.6.3.jar!/:?]
        at com.dlink.plus.FlinkSqlPlus.explainSqlColumnCA(FlinkSqlPlus.java:86) ~[dlink-core-0.6.3.jar!/:?]
......

### What you expected to happen

No exception.

### How to reproduce

devops >  click cancelled job's DataMap tab > monitor dink.log (tail -f dink.log)

### Version

0.6.3-SNAPSHOT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
看下 sql

**Comment by aiwenmo** [comment]
Hi.Look at your sql.
