### ISSUE TITLE
[Bug] [FLink SQL YARN]  Flink sql yarn application  configure cluster error

### ISSUE THREAD

**Issue by lpn666** [DataLinkDC/dlink#711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

When  I configure  the yarn application  and push the 'test' button , I got an error.
I have put the dlink-app-1.14-0.6.5-jar-with-dependencies.jar file into hdfs dir.
I have configured  hadoop_home  in  auto.sh.

![image](https://user-images.githubusercontent.com/26716574/178673008-3e6ec234-1183-4884-8899-340ef6d921d3.png)

### What you expected to happen

Caused by: java.util.ServiceConfigurationError: com.dlink.gateway.Gateway: Provider com.dlink.gateway.yarn.YarnApplicationGateway could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_181]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_181]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_181]
	at com.dlink.gateway.Gateway.get(Gateway.java:29) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.gateway.Gateway.build(Gateway.java:39) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.job.JobManager.testGateway(JobManager.java:537) ~[dlink-core-0.6.5.jar!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl.testGateway(ClusterConfigurationServiceImpl.java:80) ~[classes!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$FastClassBySpringCGLIB$$4d2e2281.invoke(<generated>) ~[classes!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$EnhancerBySpringCGLIB$$fdd1b0a1.testGateway(<generated>) ~[classes!/:?]
	at com.dlink.controller.ClusterConfigurationController.testConnect(ClusterConfigurationController.java:104) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.15.jar!/:5.3.15]
	... 42 more
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/client/deployment/ClusterRetrieveException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_181]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_181]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_181]
	at com.dlink.gateway.Gateway.get(Gateway.java:29) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.gateway.Gateway.build(Gateway.java:39) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.job.JobManager.testGateway(JobManager.java:537) ~[dlink-core-0.6.5.jar!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl.testGateway(ClusterConfigurationServiceImpl.java:80) ~[classes!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$FastClassBySpringCGLIB$$4d2e2281.invoke(<generated>) ~[classes!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$EnhancerBySpringCGLIB$$fdd1b0a1.testGateway(<generated>) ~[classes!/:?]
	at com.dlink.controller.ClusterConfigurationController.testConnect(ClusterConfigurationController.java:104) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.15.jar!/:5.3.15]
	... 42 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.client.deployment.ClusterRetrieveException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[dlink-admin-0.6.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_181]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[?:1.8.0_181]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_181]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_181]
	at com.dlink.gateway.Gateway.get(Gateway.java:29) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.gateway.Gateway.build(Gateway.java:39) ~[dlink-gateway-0.6.5.jar!/:?]
	at com.dlink.job.JobManager.testGateway(JobManager.java:537) ~[dlink-core-0.6.5.jar!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl.testGateway(ClusterConfigurationServiceImpl.java:80) ~[classes!/:?]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$FastClassBySpringCGLIB$$4d2e2281.invoke(<generated>) ~[classes!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at com.dlink.service.impl.ClusterConfigurationServiceImpl$$EnhancerBySpringCGLIB$$fdd1b0a1.testGateway(<generated>) ~[classes!/:?]
	at com.dlink.controller.ClusterConfigurationController.testConnect(ClusterConfigurationController.java:104) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
	... 42 more

### How to reproduce

Just do like what I said.

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
What files do you have in the 'dlink/plugins' path？

**Comment by lpn666** [comment]
but I have put flink dependencies on hdfs, and configured  the lib path.

**Comment by aiwenmo** [comment]
You also need to put flink dependencies on 'dlink/plugins'.

**Comment by lpn666** [comment]
> You also need to put flink dependencies on 'dlink/plugins'.

I put all my jar files on my  flink/lib directory， and it  doesn't   work either ,  now the dlink can't start.
![image](https://user-images.githubusercontent.com/26716574/178865956-d17648b2-3217-4087-8b69-aa13617432a4.png)

![image](https://user-images.githubusercontent.com/26716574/178866268-a6785402-e85b-4a14-89e3-892e06697b36.png)

**Comment by lpn666** [comment]
it's work normally  when I use streamx freamwork  and  flink standlone mode.

**Comment by aiwenmo** [comment]
Resolve dependency conflicts.

**Comment by lpn666** [comment]
> 
Are there any dependencies that are necessary，I tried  few times  but failed.

**Comment by aiwenmo** [comment]
Remove all connectors first, and then add them one by one for testing.

**Comment by lpn666** [comment]
I strongly recommend that you give a necessary dependency list .

**Comment by aiwenmo** [comment]
http://www.dlink.top/docs/next/build_deploy/deploy

**Comment by lpn666** [comment]
> http://www.dlink.top/docs/next/build_deploy/deploy

It's okay then .  Thank's very much.  
By the way ,  the address u gave to download the shard jar is not accressible.
U can change into this :  https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/flink/flink-shaded-hadoop-3-uber/3.1.1.7.2.9.0-173-9.0/

**Comment by aiwenmo** [comment]
Thx.
