### ISSUE TITLE
application 模式下报：SQL parse failed. Non-query expression encountered in illegal context

### ISSUE THREAD

**Issue by Olave** [DataLinkDC/dlink#718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink 1.13.5
dlink 0.6.5
hadoop 2.7.2

dlink plugins
![image](https://user-images.githubusercontent.com/23080394/179192231-d59f7a62-1f7b-4fdc-96c8-35abb36d1daf.png)

![image](https://user-images.githubusercontent.com/23080394/179192342-2aec6470-e3e2-4bfc-976c-489d597a1d33.png)

![image](https://user-images.githubusercontent.com/23080394/179192527-ad4d77f5-2840-4847-af4e-a13e6b10e8a8.png)

![7438243548ab1b30b1931a40f8d666e](https://user-images.githubusercontent.com/23080394/179191478-59f84ae5-672a-4f12-a5fd-5fe9b55cbec4.png)

sql检查未报错
![image](https://user-images.githubusercontent.com/23080394/179191789-c8f9f77d-f3f8-4157-800d-f4a4bcb2dc7a.png)

flink 配置
![75019d2edab908ecf9ff349ada4e88d](https://user-images.githubusercontent.com/23080394/179191564-ef09186f-8edf-46ed-80cc-dc908a980f40.png)

![f494c58777cb566eda1465e6e1e47eb](https://user-images.githubusercontent.com/23080394/179191678-8210a5bd-22a7-43f4-b4ee-11b26e538f34.png)

### What you expected to happen

# hdfs dfs -cat /yarn/logs/nodemanager/aggregation/root/logs/application_16561-nodemanager-service.default.svc.cluster.local_44239
▒▒h▒▒׶9▒A@▒▒▒P  VERSIONAPPLICATION_ACLAPPLICATION_OWNERroot(&container_1656125978228_0033_01_000001▒50jobmanager.err656SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tmp/hadoop-root/nm-local-dir/filecache/25/log4j-slf4j-impl-2.16.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/hadoop-root/nm-local-dir/filecache/32/phoenix-5.0.0-HBase-2.0-client.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.4/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
jobmanager.out1291614:58:38.524 [flink-akka.actor.default-dispatcher-6] ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint - Fatal error occurred in the cluster entrypo
org.apache.flink.util.FlinkException: Application failed unexpectedly.
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAndShutdownClusterAsync$0(ApplicationDispatcherBootstrap.java:170)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_131]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:257) ~[flink-dist_2.11-1.13
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$1(ApplicationDispatcherBootstrap.java:212) ~[flink-dist_2.11-
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:159) [flink-dist_2.11-1.
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [flink-dist_2.11-1.13.5.jar:1.13.5]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44) [flink-dist_2.11-1.13.5.jar:1.13.5]
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [flink-dist_2.11-1.13.5.jar:1.13.5]
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [flink-dist_2.11-1.13.5.jar:1.13.5]
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [flink-dist_2.11-1.13.5.jar:1.13.5]
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [flink-dist_2.11-1.13.5.jar:1.13.5]
Caused by: java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943) ~[?:1.8.0_131]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_131]
        ... 13 more
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
        ... 11 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: SQL parse failed. Non-query expression encountered in illegal context
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.11-1.13
        ... 10 more
Caused by: org.apache.flink.table.api.SqlParserException: SQL parse failed. Non-query expression encountered in illegal context
        at org.apache.flink.table.planner.parse.CalciteParser.parse(CalciteParser.java:56) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:98) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at com.dlink.executor.Executor.executeSql(Executor.java:221) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.executor.Executor.submitSql(Executor.java:340) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.flinksql.Submiter.submit(Submiter.java:124) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.MainApp.main(MainApp.java:25) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.11-1.13
        ... 10 more
Caused by: org.apache.calcite.sql.parser.SqlParseException: Non-query expression encountered in illegal context
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.convertException(FlinkSqlParserImpl.java:452) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.normalizeException(FlinkSqlParserImpl.java:215) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.parser.SqlParser.handleException(SqlParser.java:140) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.parser.SqlParser.parseQuery(SqlParser.java:155) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.parser.SqlParser.parseStmt(SqlParser.java:180) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.planner.parse.CalciteParser.parse(CalciteParser.java:54) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:98) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at com.dlink.executor.Executor.executeSql(Executor.java:221) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.executor.Executor.submitSql(Executor.java:340) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.flinksql.Submiter.submit(Submiter.java:124) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.MainApp.main(MainApp.java:25) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.11-1.13
        ... 10 more
Caused by: org.apache.calcite.runtime.CalciteException: Non-query expression encountered in illegal context
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:467) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:560) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:883) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:868) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.checkNonQueryExpression(FlinkSqlParserImpl.java:375) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.Expression3(FlinkSqlParserImpl.java:19036) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.Expression2b(FlinkSqlParserImpl.java:18705) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.Expression2(FlinkSqlParserImpl.java:18746) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.Expression(FlinkSqlParserImpl.java:18677) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.LeafQueryOrExpr(FlinkSqlParserImpl.java:18654) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.QueryOrExpr(FlinkSqlParserImpl.java:18112) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.OrderedQueryOrExpr(FlinkSqlParserImpl.java:568) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.SqlStmt(FlinkSqlParserImpl.java:3885) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.SqlStmtEof(FlinkSqlParserImpl.java:3924) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.sql.parser.impl.FlinkSqlParserImpl.parseSqlStmtEof(FlinkSqlParserImpl.java:263) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.parser.SqlParser.parseQuery(SqlParser.java:153) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.calcite.sql.parser.SqlParser.parseStmt(SqlParser.java:180) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.planner.parse.CalciteParser.parse(CalciteParser.java:54) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:98) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724) ~[flink-table-blink_2.11-1.13.5.jar:1.13.5]
        at com.dlink.executor.Executor.executeSql(Executor.java:221) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.executor.Executor.submitSql(Executor.java:340) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.flinksql.Submiter.submit(Submiter.java:124) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at com.dlink.app.MainApp.main(MainApp.java:25) ~[dlink-app-1.13-0.6.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.11-1.13.5.jar:1.13.5]
        at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242) ~[flink-dist_2.11-1.13
        ... 10 more

### How to reproduce

以上环境

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
plugins下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar
