### ISSUE TITLE
[Bug] [dlink] com.dlink.exception.WebExceptionHandler

### ISSUE THREAD

**Issue by ChewJ404** [DataLinkDC/dlink#798]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

- dlink 版本号为 0.6.4
- flink-1.14.5-bin-scala_2.12.tgz

---
1 已经 将 flink lib下 所有包 拷贝到 dlink  `opt/dinky/plugins` 目录下
2 已经将 `/opt/dinky/extends` 下的 `dlink-client-1.14-0.6.4.jar` 拷贝至`/opt/dinky/lib/dlink-client-1.14-0.6.4.jar` 并且已删除原有`dlink-client-1.13-0.6.4.jar`
### 问题1
启动报错  但能启动成功
```
[dlink] 2022-07-20 16:05:12.266 ERROR com.dlink.exception.WebExceptionHandler 45 unknownException - ERROR: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'java.util.Map org.apache.flink.table.api.EnvironmentSettings.toExecutorProperties()'
2022-07-20T08:05:12.277275600Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) [spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277278300Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277280100Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277281900Z 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277283700Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277285300Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277287000Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277288700Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277290500Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277292200Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.56.jar!/:?]
2022-07-20T08:05:12.277293800Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277295500Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277297200Z 	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124) [druid-1.2.8.jar!/:1.2.8]
2022-07-20T08:05:12.277299700Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277301600Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277303300Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277313300Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277315200Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277316900Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277318500Z 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277320100Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277321800Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277323600Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277325300Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277327000Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277328700Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277330400Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277332100Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277333700Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277335600Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277337500Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277339500Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277341300Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277343000Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277344600Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277346200Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277347900Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277351500Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277353400Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277355200Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277357000Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277358700Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.56.jar!/:?]
2022-07-20T08:05:12.277360400Z 	at java.lang.Thread.run(Unknown Source) [?:?]
2022-07-20T08:05:12.277361900Z Caused by: java.lang.NoSuchMethodError: 'java.util.Map org.apache.flink.table.api.EnvironmentSettings.toExecutorProperties()'
2022-07-20T08:05:12.277363600Z 	at com.dlink.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:137) ~[dlink-client-1.13-0.6.5.jar:?]
2022-07-20T08:05:12.277365200Z 	at com.dlink.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:111) ~[dlink-client-1.13-0.6.5.jar:?]
2022-07-20T08:05:12.277367300Z 	at com.dlink.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:97) ~[dlink-client-1.13-0.6.5.jar:?]
2022-07-20T08:05:12.277369100Z 	at com.dlink.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:30) ~[dlink-executor-0.6.4.jar!/:?]
2022-07-20T08:05:12.277370900Z 	at com.dlink.executor.Executor.initStreamExecutionEnvironment(Executor.java:160) ~[dlink-executor-0.6.4.jar!/:?]
2022-07-20T08:05:12.277372700Z 	at com.dlink.executor.Executor.init(Executor.java:122) ~[dlink-executor-0.6.4.jar!/:?]
2022-07-20T08:05:12.277374300Z 	at com.dlink.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:25) ~[dlink-executor-0.6.4.jar!/:?]
2022-07-20T08:05:12.277376000Z 	at com.dlink.executor.Executor.buildLocalExecutor(Executor.java:71) ~[dlink-executor-0.6.4.jar!/:?]
2022-07-20T08:05:12.277377600Z 	at com.dlink.job.JobManager.createExecutor(JobManager.java:168) ~[dlink-core-0.6.4.jar!/:?]
2022-07-20T08:05:12.277379200Z 	at com.dlink.job.JobManager.createExecutorWithSession(JobManager.java:186) ~[dlink-core-0.6.4.jar!/:?]
2022-07-20T08:05:12.277381000Z 	at com.dlink.job.JobManager.init(JobManager.java:211) ~[dlink-core-0.6.4.jar!/:?]
2022-07-20T08:05:12.277382700Z 	at com.dlink.job.JobManager.build(JobManager.java:135) ~[dlink-core-0.6.4.jar!/:?]
2022-07-20T08:05:12.277384400Z 	at com.dlink.service.impl.StudioServiceImpl.executeFlinkSql(StudioServiceImpl.java:101) ~[classes!/:?]
2022-07-20T08:05:12.277386100Z 	at com.dlink.service.impl.StudioServiceImpl.executeSql(StudioServiceImpl.java:91) ~[classes!/:?]
2022-07-20T08:05:12.277387700Z 	at com.dlink.controller.StudioController.executeSql(StudioController.java:42) ~[classes!/:?]
2022-07-20T08:05:12.277391200Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2022-07-20T08:05:12.277392900Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2022-07-20T08:05:12.277394400Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2022-07-20T08:05:12.277396200Z 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
2022-07-20T08:05:12.277397800Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277399700Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277401700Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277403500Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277405300Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277407000Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar!/:5.3.15]
2022-07-20T08:05:12.277408700Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.15.jar!/:5.3.15]
```
---

### What you expected to happen

1. 拷贝 doris cdc  至 `/opt/dinky/plugins/flink-doris-connector-1.14_2.12-1.0.3.jar` 和 flink的 lib 目录
2. 用/opt/flink/bin/  sql-client.sh  模式  执行 doris 查询  成功
```

CREATE TABLE flink_doris_select (
    `id` BIGINT,
    `name` STRING,
    __DORIS_DELETE_SIGN__ TINYINT
     ) 
     WITH (
           'connector' = 'doris',
           'fenodes' = '192.168.12.222:8030',
           'table.identifier' = 'dataease.user_sink',
           'username' = 'root',
           'password' = '123456'
 );
SELECT * from flink_doris_select；

SQL Query Result (Table)                                                                                     

     id                           name    __DORIS_DELETE_SIGN__
      1                            aaa                     0

```
但是在  dlink 执行sql 作业  报错 流程如下 

123

### How to reproduce

1. 编写语句后  执行 FlinkSql 语法和逻辑检查 提示如下错误
```
 Modify DML
语法有误
逻辑有误
2022-07-30T16:09:20.787566
SELECT * from flink_doris_select;  
```
2. 点击 `获取当前的 FlinkSql 的执行图` 报错
```
org.apache.flink.table.api.SqlParserException: SQL parse failed. Encountered ";" at line 1, column 33.
2022-07-30T08:13:49.828694900Z Was expecting one of:
2022-07-30T08:13:49.828716200Z     <EOF> 
2022-07-30T08:13:49.828725900Z     "AS" ...
2022-07-30T08:13:49.828729700Z     "EXCEPT" ...
2022-07-30T08:13:49.828734400Z     "EXTEND" ...
2022-07-30T08:13:49.828738200Z     "FETCH" ...
2022-07-30T08:13:49.828742100Z     "FOR" ...
2022-07-30T08:13:49.828804400Z     "GROUP" ...
2022-07-30T08:13:49.828810900Z     "HAVING" ...
2022-07-30T08:13:49.828816900Z     "INTERSECT" ...
2022-07-30T08:13:49.828821400Z     "LIMIT" ...
2022-07-30T08:13:49.828825200Z     "MATCH_RECOGNIZE" ...
2022-07-30T08:13:49.828830100Z     "OFFSET" ...
2022-07-30T08:13:49.828835200Z     "ORDER" ...
2022-07-30T08:13:49.828839000Z     "PIVOT" ...
2022-07-30T08:13:49.828843800Z     "MINUS" ...
2022-07-30T08:13:49.828848400Z     "TABLESAMPLE" ...
2022-07-30T08:13:49.828852200Z     "UNION" ...
2022-07-30T08:13:49.828856000Z     "WHERE" ...
2022-07-30T08:13:49.828860900Z     "WINDOW" ...
2022-07-30T08:13:49.828867200Z     "(" ...
2022-07-30T08:13:49.828871600Z     <BRACKET_QUOTED_IDENTIFIER> ...
2022-07-30T08:13:49.828877000Z     <QUOTED_IDENTIFIER> ...
2022-07-30T08:13:49.828881000Z     <BACK_QUOTED_IDENTIFIER> ...
2022-07-30T08:13:49.828885200Z     <HYPHENATED_IDENTIFIER> ...
2022-07-30T08:13:49.828888500Z     <IDENTIFIER> ...
2022-07-30T08:13:49.828892300Z     <UNICODE_QUOTED_IDENTIFIER> ...
2022-07-30T08:13:49.828894900Z     "/*+" ...
2022-07-30T08:13:49.828898000Z     "NATURAL" ...
2022-07-30T08:13:49.828900600Z     "JOIN" ...
2022-07-30T08:13:49.828904900Z     "INNER" ...
2022-07-30T08:13:49.828909400Z     "LEFT" ...
2022-07-30T08:13:49.828913300Z     "RIGHT" ...
2022-07-30T08:13:49.828917000Z     "FULL" ...
2022-07-30T08:13:49.828974800Z     "CROSS" ...
2022-07-30T08:13:49.828984000Z     "," ...
2022-07-30T08:13:49.828988500Z     "OUTER" ...
2022-07-30T08:13:49.828992400Z     "." ...
2022-07-30T08:13:49.828996200Z     
2022-07-30T08:13:49.829001800Z 	at org.apache.flink.table.planner.parse.CalciteParser.parse(CalciteParser.java:56)
2022-07-30T08:13:49.829006900Z 	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:98)
2022-07-30T08:13:49.829028400Z 	at com.dlink.executor.CustomTableEnvironmentImpl.getStreamGraphFromInserts(CustomTableEnvironmentImpl.java:228)
2022-07-30T08:13:49.829037000Z 	at com.dlink.executor.CustomTableEnvironmentImpl.getJobGraphFromInserts(CustomTableEnvironmentImpl.java:253)
2022-07-30T08:13:49.829068500Z 	at com.dlink.executor.CustomTableEnvironmentImpl.getJobPlanInfo(CustomTableEnvironmentImpl.java:222)
2022-07-30T08:13:49.829088200Z 	at com.dlink.executor.Executor.getJobPlanInfo(Executor.java:292)
2022-07-30T08:13:49.829091300Z 	at com.dlink.explainer.Explainer.getJobPlanInfo(Explainer.java:291)
2022-07-30T08:13:49.829132000Z 	at com.dlink.job.JobManager.getJobPlanJson(JobManager.java:472)
2022-07-30T08:13:49.829138700Z 	at com.dlink.service.impl.StudioServiceImpl.getJobPlan(StudioServiceImpl.java:208)
2022-07-30T08:13:49.829288400Z 	at com.dlink.controller.StudioController.getJobPlan(StudioController.java:68)
2022-07-30T08:13:49.829333200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-30T08:13:49.829530800Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-07-30T08:13:49.829604300Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-07-30T08:13:49.829746200Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-07-30T08:13:49.829818200Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2022-07-30T08:13:49.829842000Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
2022-07-30T08:13:49.830249000Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
2022-07-30T08:13:49.830442900Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
2022-07-30T08:13:49.830510100Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
2022-07-30T08:13:49.830805500Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2022-07-30T08:13:49.830869600Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
2022-07-30T08:13:49.830893200Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
2022-07-30T08:13:49.831210300Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2022-07-30T08:13:49.831479500Z 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
2022-07-30T08:13:49.831507800Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
2022-07-30T08:13:49.831514500Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2022-07-30T08:13:49.831521300Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
2022-07-30T08:13:49.831712400Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
2022-07-30T08:13:49.831744900Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.831770900Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2022-07-30T08:13:49.831777400Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2022-07-30T08:13:49.831890300Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.831918300Z 	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
2022-07-30T08:13:49.832165700Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2022-07-30T08:13:49.832194100Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.832314100Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2022-07-30T08:13:49.832344600Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2022-07-30T08:13:49.832725700Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2022-07-30T08:13:49.832872500Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.832916200Z 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2022-07-30T08:13:49.832922900Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2022-07-30T08:13:49.833126500Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2022-07-30T08:13:49.833155900Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.833163400Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2022-07-30T08:13:49.833223200Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2022-07-30T08:13:49.833330800Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2022-07-30T08:13:49.833364500Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2022-07-30T08:13:49.833576000Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
2022-07-30T08:13:49.833605400Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2022-07-30T08:13:49.833613400Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
2022-07-30T08:13:49.833764200Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
2022-07-30T08:13:49.833916300Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2022-07-30T08:13:49.834032900Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2022-07-30T08:13:49.834191700Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2022-07-30T08:13:49.834379300Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
2022-07-30T08:13:49.834586600Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2022-07-30T08:13:49.834649500Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
2022-07-30T08:13:49.834719400Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
2022-07-30T08:13:49.834817400Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2022-07-30T08:13:49.834846700Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2022-07-30T08:13:49.834958500Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2022-07-30T08:13:49.835079300Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2022-07-30T08:13:49.835194000Z 	at java.base/java.lang.Thread.run(Unknown Source)
2022-07-30T08:13:49.835835200Z Caused by: org.apache.calcite.sql.parser.SqlParseException: Encountered ";" at line 1, column 33.
```
3.  点击 执行当前的 SQL 提示 还是  查询语句 **;**  问题 ，去掉 **;**后 保存 再执行 就成功 **为啥 结尾非要 要去掉 ; 这么设计  -，-** 

### Version

0.6.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
你可以更新至 0.6.6 来避免这个问题。为什么要在结尾去掉 ; 呢，是 Dinky 的分割符导致的，你可以在末尾加个换行就能被分隔符匹配到。
